//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3082
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerWebApp.otherinsurance {
    
    
    public partial class PolicyInput {
        
        /// <summary>
        /// ScriptManager1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::AjaxControlToolkit.ToolkitScriptManager ScriptManager1;
        
        /// <summary>
        /// pagemode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden pagemode;
        
        /// <summary>
        /// dxeAddCallback 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxCallback.ASPxCallback dxeAddCallback;
        
        /// <summary>
        /// dxeSaveCallback 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxCallback.ASPxCallback dxeSaveCallback;
        
        /// <summary>
        /// dxeSaveAndCheckCallback 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxCallback.ASPxCallback dxeSaveAndCheckCallback;
        
        /// <summary>
        /// dxeAuditOkCallback 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxCallback.ASPxCallback dxeAuditOkCallback;
        
        /// <summary>
        /// nppagecontent 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel nppagecontent;
        
        /// <summary>
        /// insuranceDetailTabPage 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxTabControl.ASPxPageControl insuranceDetailTabPage;
        
        /// <summary>
        /// npbasicheader 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel npbasicheader;
        
        /// <summary>
        /// img_npbasicheader 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton img_npbasicheader;
        
        /// <summary>
        /// lbl_npbasicheader 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_npbasicheader;
        
        /// <summary>
        /// npbasicdetail 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel npbasicdetail;
        
        /// <summary>
        /// dxetxtPolicyID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtPolicyID;
        
        /// <summary>
        /// pplcid 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden pplcid;
        
        /// <summary>
        /// dxetxtPolicyNo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtPolicyNo;
        
        /// <summary>
        /// dxechkTogether 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxCheckBox dxechkTogether;
        
        /// <summary>
        /// dxechkFlagReinsure 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxCheckBox dxechkFlagReinsure;
        
        /// <summary>
        /// dxetxtProdTypeName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtProdTypeName;
        
        /// <summary>
        /// ptid 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ptid;
        
        /// <summary>
        /// img1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage img1;
        
        /// <summary>
        /// dxetxtCustomer 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtCustomer;
        
        /// <summary>
        /// cusid 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden cusid;
        
        /// <summary>
        /// imgNewCustomer 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage imgNewCustomer;
        
        /// <summary>
        /// imgSelectCustomer 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage imgSelectCustomer;
        
        /// <summary>
        /// dxetxtBeneficiary 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtBeneficiary;
        
        /// <summary>
        /// dxeddlDeptID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxComboBox dxeddlDeptID;
        
        /// <summary>
        /// dxeddlSalesId 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxComboBox dxeddlSalesId;
        
        /// <summary>
        /// dxeddlGatheringType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxComboBox dxeddlGatheringType;
        
        /// <summary>
        /// dxeddlOperationType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxComboBox dxeddlOperationType;
        
        /// <summary>
        /// dxeddlSourceTypeID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxComboBox dxeddlSourceTypeID;
        
        /// <summary>
        /// dxeStartDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxDateEdit dxeStartDate;
        
        /// <summary>
        /// dxeEndDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxDateEdit dxeEndDate;
        
        /// <summary>
        /// dxetxtCreatePerson 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtCreatePerson;
        
        /// <summary>
        /// dxedtCreateTime 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxDateEdit dxedtCreateTime;
        
        /// <summary>
        /// dxetxtStage 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtStage;
        
        /// <summary>
        /// dxebtntopSave 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxButton dxebtntopSave;
        
        /// <summary>
        /// cpeBasic 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeBasic;
        
        /// <summary>
        /// npGridPolicyItemHeader 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel npGridPolicyItemHeader;
        
        /// <summary>
        /// img_npGridPolicyItem 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton img_npGridPolicyItem;
        
        /// <summary>
        /// lbl_npGridPolicyItem 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_npGridPolicyItem;
        
        /// <summary>
        /// npGridPolicyItemDetail 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel npGridPolicyItemDetail;
        
        /// <summary>
        /// gridPolicyItem 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView gridPolicyItem;
        
        /// <summary>
        /// cpeGridPolicyItem 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeGridPolicyItem;
        
        /// <summary>
        /// npCostSummaryHeader 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel npCostSummaryHeader;
        
        /// <summary>
        /// img_npCostSummaryHeader 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton img_npCostSummaryHeader;
        
        /// <summary>
        /// lbl_npCostSummaryHeader 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_npCostSummaryHeader;
        
        /// <summary>
        /// npCostSummaryDetail 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel npCostSummaryDetail;
        
        /// <summary>
        /// dxetxtCoverage 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtCoverage;
        
        /// <summary>
        /// dxetxtPremiumRate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtPremiumRate;
        
        /// <summary>
        /// dxetxtProcessRate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtProcessRate;
        
        /// <summary>
        /// dxeddlCurrency 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxComboBox dxeddlCurrency;
        
        /// <summary>
        /// dxetxtPremium 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtPremium;
        
        /// <summary>
        /// dxetxtProcess 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtProcess;
        
        /// <summary>
        /// dxetxtConversionRate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtConversionRate;
        
        /// <summary>
        /// dxetxtPremiumBase 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtPremiumBase;
        
        /// <summary>
        /// dxetxtProcessBase 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtProcessBase;
        
        /// <summary>
        /// CollapsiblePanelExtender2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::AjaxControlToolkit.CollapsiblePanelExtender CollapsiblePanelExtender2;
        
        /// <summary>
        /// npPolicyCompanyHeader 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel npPolicyCompanyHeader;
        
        /// <summary>
        /// img_npPolicyCompanyHeader 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton img_npPolicyCompanyHeader;
        
        /// <summary>
        /// lbl_npPolicyCompanyHeader 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_npPolicyCompanyHeader;
        
        /// <summary>
        /// npPolicyCompanyDetail 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel npPolicyCompanyDetail;
        
        /// <summary>
        /// gridCarrier 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView gridCarrier;
        
        /// <summary>
        /// btngridCarrierTogether 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView.GridViewCommandColumnCustomButton btngridCarrierTogether;
        
        /// <summary>
        /// CollapsiblePanelExtender1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::AjaxControlToolkit.CollapsiblePanelExtender CollapsiblePanelExtender1;
        
        /// <summary>
        /// tblcellfilesUploadControl 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tblcellfilesUploadControl;
        
        /// <summary>
        /// filesUploadControl 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxUploadControl.ASPxUploadControl filesUploadControl;
        
        /// <summary>
        /// tblcellgridDocList 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tblcellgridDocList;
        
        /// <summary>
        /// gridDocList 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView gridDocList;
        
        /// <summary>
        /// ContentControl2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxClasses.ContentControl ContentControl2;
        
        /// <summary>
        /// tblcellgridPeriod 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tblcellgridPeriod;
        
        /// <summary>
        /// gridPeriod 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView gridPeriod;
        
        /// <summary>
        /// ContentControl1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxClasses.ContentControl ContentControl1;
        
        /// <summary>
        /// dxetxtIDNo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox dxetxtIDNo;
        
        /// <summary>
        /// dxeCheckDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxDateEdit dxeCheckDate;
        
        /// <summary>
        /// dxeMemo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxMemo dxeMemo;
        
        /// <summary>
        /// tbltrAuditExecuteAction 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow tbltrAuditExecuteAction;
        
        /// <summary>
        /// dxebtnAuditOk 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxButton dxebtnAuditOk;
        
        /// <summary>
        /// dxebtnAuditClose 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxButton dxebtnAuditClose;
        
        /// <summary>
        /// npNewExecuteAction 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel npNewExecuteAction;
        
        /// <summary>
        /// tblNewExecuteAction 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable tblNewExecuteAction;
        
        /// <summary>
        /// dxebtnBottomAdd 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxButton dxebtnBottomAdd;
        
        /// <summary>
        /// dxebtnBottomSave 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxButton dxebtnBottomSave;
        
        /// <summary>
        /// dxebtnBottomCheck 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxButton dxebtnBottomCheck;
        
        /// <summary>
        /// dxebtnCancel 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxButton dxebtnCancel;
        
        /// <summary>
        /// dxeClose 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxButton dxeClose;
    }
}
