//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace BrokerWebApp.Report.rpt {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsTYGH")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsTYGH : global::System.Data.DataSet {
        
        private TYGHDataTable tableTYGH;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsTYGH() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsTYGH(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["TYGH"] != null)) {
                    base.Tables.Add(new TYGHDataTable(ds.Tables["TYGH"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TYGHDataTable TYGH {
            get {
                return this.tableTYGH;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsTYGH cln = ((dsTYGH)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["TYGH"] != null)) {
                    base.Tables.Add(new TYGHDataTable(ds.Tables["TYGH"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableTYGH = ((TYGHDataTable)(base.Tables["TYGH"]));
            if ((initTable == true)) {
                if ((this.tableTYGH != null)) {
                    this.tableTYGH.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsTYGH";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsTYGH.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTYGH = new TYGHDataTable();
            base.Tables.Add(this.tableTYGH);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeTYGH() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsTYGH ds = new dsTYGH();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void TYGHRowChangeEventHandler(object sender, TYGHRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TYGHDataTable : global::System.Data.TypedTableBase<TYGHRow> {
            
            private global::System.Data.DataColumn columnNY;
            
            private global::System.Data.DataColumn columnCC_BF_BQ;
            
            private global::System.Data.DataColumn columnCC_BF_LJ;
            
            private global::System.Data.DataColumn columnCC_JJF_BQ;
            
            private global::System.Data.DataColumn columnCC_JJF_LJ;
            
            private global::System.Data.DataColumn columnCC_ZXF_BQ;
            
            private global::System.Data.DataColumn columnCC_ZXF_LJ;
            
            private global::System.Data.DataColumn columnRS_BF_BQ;
            
            private global::System.Data.DataColumn columnRS_BF_LJ;
            
            private global::System.Data.DataColumn columnRS_JJF_BQ;
            
            private global::System.Data.DataColumn columnRS_JJF_LJ;
            
            private global::System.Data.DataColumn columnRS_ZXF_BQ;
            
            private global::System.Data.DataColumn columnRS_ZXF_LJ;
            
            private global::System.Data.DataColumn columnHJ_BF_BQ;
            
            private global::System.Data.DataColumn columnHJ_BF_LJ;
            
            private global::System.Data.DataColumn columnHJ_JJF_BQ;
            
            private global::System.Data.DataColumn columnHJ_JJF_LJ;
            
            private global::System.Data.DataColumn columnHJ_ZXF_BQ;
            
            private global::System.Data.DataColumn columnHJ_ZXF_LJ;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TYGHDataTable() {
                this.TableName = "TYGH";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TYGHDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected TYGHDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NYColumn {
                get {
                    return this.columnNY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CC_BF_BQColumn {
                get {
                    return this.columnCC_BF_BQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CC_BF_LJColumn {
                get {
                    return this.columnCC_BF_LJ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CC_JJF_BQColumn {
                get {
                    return this.columnCC_JJF_BQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CC_JJF_LJColumn {
                get {
                    return this.columnCC_JJF_LJ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CC_ZXF_BQColumn {
                get {
                    return this.columnCC_ZXF_BQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CC_ZXF_LJColumn {
                get {
                    return this.columnCC_ZXF_LJ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RS_BF_BQColumn {
                get {
                    return this.columnRS_BF_BQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RS_BF_LJColumn {
                get {
                    return this.columnRS_BF_LJ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RS_JJF_BQColumn {
                get {
                    return this.columnRS_JJF_BQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RS_JJF_LJColumn {
                get {
                    return this.columnRS_JJF_LJ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RS_ZXF_BQColumn {
                get {
                    return this.columnRS_ZXF_BQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RS_ZXF_LJColumn {
                get {
                    return this.columnRS_ZXF_LJ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HJ_BF_BQColumn {
                get {
                    return this.columnHJ_BF_BQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HJ_BF_LJColumn {
                get {
                    return this.columnHJ_BF_LJ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HJ_JJF_BQColumn {
                get {
                    return this.columnHJ_JJF_BQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HJ_JJF_LJColumn {
                get {
                    return this.columnHJ_JJF_LJ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HJ_ZXF_BQColumn {
                get {
                    return this.columnHJ_ZXF_BQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HJ_ZXF_LJColumn {
                get {
                    return this.columnHJ_ZXF_LJ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TYGHRow this[int index] {
                get {
                    return ((TYGHRow)(this.Rows[index]));
                }
            }
            
            public event TYGHRowChangeEventHandler TYGHRowChanging;
            
            public event TYGHRowChangeEventHandler TYGHRowChanged;
            
            public event TYGHRowChangeEventHandler TYGHRowDeleting;
            
            public event TYGHRowChangeEventHandler TYGHRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddTYGHRow(TYGHRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TYGHRow AddTYGHRow(
                        string NY, 
                        string CC_BF_BQ, 
                        string CC_BF_LJ, 
                        string CC_JJF_BQ, 
                        string CC_JJF_LJ, 
                        string CC_ZXF_BQ, 
                        string CC_ZXF_LJ, 
                        string RS_BF_BQ, 
                        string RS_BF_LJ, 
                        string RS_JJF_BQ, 
                        string RS_JJF_LJ, 
                        string RS_ZXF_BQ, 
                        string RS_ZXF_LJ, 
                        string HJ_BF_BQ, 
                        string HJ_BF_LJ, 
                        string HJ_JJF_BQ, 
                        string HJ_JJF_LJ, 
                        string HJ_ZXF_BQ, 
                        string HJ_ZXF_LJ) {
                TYGHRow rowTYGHRow = ((TYGHRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        NY,
                        CC_BF_BQ,
                        CC_BF_LJ,
                        CC_JJF_BQ,
                        CC_JJF_LJ,
                        CC_ZXF_BQ,
                        CC_ZXF_LJ,
                        RS_BF_BQ,
                        RS_BF_LJ,
                        RS_JJF_BQ,
                        RS_JJF_LJ,
                        RS_ZXF_BQ,
                        RS_ZXF_LJ,
                        HJ_BF_BQ,
                        HJ_BF_LJ,
                        HJ_JJF_BQ,
                        HJ_JJF_LJ,
                        HJ_ZXF_BQ,
                        HJ_ZXF_LJ};
                rowTYGHRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTYGHRow);
                return rowTYGHRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                TYGHDataTable cln = ((TYGHDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TYGHDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnNY = base.Columns["NY"];
                this.columnCC_BF_BQ = base.Columns["CC_BF_BQ"];
                this.columnCC_BF_LJ = base.Columns["CC_BF_LJ"];
                this.columnCC_JJF_BQ = base.Columns["CC_JJF_BQ"];
                this.columnCC_JJF_LJ = base.Columns["CC_JJF_LJ"];
                this.columnCC_ZXF_BQ = base.Columns["CC_ZXF_BQ"];
                this.columnCC_ZXF_LJ = base.Columns["CC_ZXF_LJ"];
                this.columnRS_BF_BQ = base.Columns["RS_BF_BQ"];
                this.columnRS_BF_LJ = base.Columns["RS_BF_LJ"];
                this.columnRS_JJF_BQ = base.Columns["RS_JJF_BQ"];
                this.columnRS_JJF_LJ = base.Columns["RS_JJF_LJ"];
                this.columnRS_ZXF_BQ = base.Columns["RS_ZXF_BQ"];
                this.columnRS_ZXF_LJ = base.Columns["RS_ZXF_LJ"];
                this.columnHJ_BF_BQ = base.Columns["HJ_BF_BQ"];
                this.columnHJ_BF_LJ = base.Columns["HJ_BF_LJ"];
                this.columnHJ_JJF_BQ = base.Columns["HJ_JJF_BQ"];
                this.columnHJ_JJF_LJ = base.Columns["HJ_JJF_LJ"];
                this.columnHJ_ZXF_BQ = base.Columns["HJ_ZXF_BQ"];
                this.columnHJ_ZXF_LJ = base.Columns["HJ_ZXF_LJ"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnNY = new global::System.Data.DataColumn("NY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNY);
                this.columnCC_BF_BQ = new global::System.Data.DataColumn("CC_BF_BQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCC_BF_BQ);
                this.columnCC_BF_LJ = new global::System.Data.DataColumn("CC_BF_LJ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCC_BF_LJ);
                this.columnCC_JJF_BQ = new global::System.Data.DataColumn("CC_JJF_BQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCC_JJF_BQ);
                this.columnCC_JJF_LJ = new global::System.Data.DataColumn("CC_JJF_LJ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCC_JJF_LJ);
                this.columnCC_ZXF_BQ = new global::System.Data.DataColumn("CC_ZXF_BQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCC_ZXF_BQ);
                this.columnCC_ZXF_LJ = new global::System.Data.DataColumn("CC_ZXF_LJ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCC_ZXF_LJ);
                this.columnRS_BF_BQ = new global::System.Data.DataColumn("RS_BF_BQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRS_BF_BQ);
                this.columnRS_BF_LJ = new global::System.Data.DataColumn("RS_BF_LJ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRS_BF_LJ);
                this.columnRS_JJF_BQ = new global::System.Data.DataColumn("RS_JJF_BQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRS_JJF_BQ);
                this.columnRS_JJF_LJ = new global::System.Data.DataColumn("RS_JJF_LJ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRS_JJF_LJ);
                this.columnRS_ZXF_BQ = new global::System.Data.DataColumn("RS_ZXF_BQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRS_ZXF_BQ);
                this.columnRS_ZXF_LJ = new global::System.Data.DataColumn("RS_ZXF_LJ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRS_ZXF_LJ);
                this.columnHJ_BF_BQ = new global::System.Data.DataColumn("HJ_BF_BQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHJ_BF_BQ);
                this.columnHJ_BF_LJ = new global::System.Data.DataColumn("HJ_BF_LJ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHJ_BF_LJ);
                this.columnHJ_JJF_BQ = new global::System.Data.DataColumn("HJ_JJF_BQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHJ_JJF_BQ);
                this.columnHJ_JJF_LJ = new global::System.Data.DataColumn("HJ_JJF_LJ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHJ_JJF_LJ);
                this.columnHJ_ZXF_BQ = new global::System.Data.DataColumn("HJ_ZXF_BQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHJ_ZXF_BQ);
                this.columnHJ_ZXF_LJ = new global::System.Data.DataColumn("HJ_ZXF_LJ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHJ_ZXF_LJ);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TYGHRow NewTYGHRow() {
                return ((TYGHRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TYGHRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(TYGHRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TYGHRowChanged != null)) {
                    this.TYGHRowChanged(this, new TYGHRowChangeEvent(((TYGHRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TYGHRowChanging != null)) {
                    this.TYGHRowChanging(this, new TYGHRowChangeEvent(((TYGHRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TYGHRowDeleted != null)) {
                    this.TYGHRowDeleted(this, new TYGHRowChangeEvent(((TYGHRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TYGHRowDeleting != null)) {
                    this.TYGHRowDeleting(this, new TYGHRowChangeEvent(((TYGHRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveTYGHRow(TYGHRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsTYGH ds = new dsTYGH();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TYGHDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class TYGHRow : global::System.Data.DataRow {
            
            private TYGHDataTable tableTYGH;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TYGHRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTYGH = ((TYGHDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NY {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.NYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“NY”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.NYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CC_BF_BQ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.CC_BF_BQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“CC_BF_BQ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.CC_BF_BQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CC_BF_LJ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.CC_BF_LJColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“CC_BF_LJ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.CC_BF_LJColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CC_JJF_BQ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.CC_JJF_BQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“CC_JJF_BQ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.CC_JJF_BQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CC_JJF_LJ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.CC_JJF_LJColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“CC_JJF_LJ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.CC_JJF_LJColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CC_ZXF_BQ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.CC_ZXF_BQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“CC_ZXF_BQ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.CC_ZXF_BQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CC_ZXF_LJ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.CC_ZXF_LJColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“CC_ZXF_LJ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.CC_ZXF_LJColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RS_BF_BQ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.RS_BF_BQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“RS_BF_BQ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.RS_BF_BQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RS_BF_LJ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.RS_BF_LJColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“RS_BF_LJ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.RS_BF_LJColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RS_JJF_BQ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.RS_JJF_BQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“RS_JJF_BQ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.RS_JJF_BQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RS_JJF_LJ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.RS_JJF_LJColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“RS_JJF_LJ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.RS_JJF_LJColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RS_ZXF_BQ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.RS_ZXF_BQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“RS_ZXF_BQ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.RS_ZXF_BQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RS_ZXF_LJ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.RS_ZXF_LJColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“RS_ZXF_LJ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.RS_ZXF_LJColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HJ_BF_BQ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.HJ_BF_BQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“HJ_BF_BQ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.HJ_BF_BQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HJ_BF_LJ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.HJ_BF_LJColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“HJ_BF_LJ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.HJ_BF_LJColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HJ_JJF_BQ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.HJ_JJF_BQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“HJ_JJF_BQ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.HJ_JJF_BQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HJ_JJF_LJ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.HJ_JJF_LJColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“HJ_JJF_LJ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.HJ_JJF_LJColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HJ_ZXF_BQ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.HJ_ZXF_BQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“HJ_ZXF_BQ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.HJ_ZXF_BQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HJ_ZXF_LJ {
                get {
                    try {
                        return ((string)(this[this.tableTYGH.HJ_ZXF_LJColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TYGH”中列“HJ_ZXF_LJ”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTYGH.HJ_ZXF_LJColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNYNull() {
                return this.IsNull(this.tableTYGH.NYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNYNull() {
                this[this.tableTYGH.NYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCC_BF_BQNull() {
                return this.IsNull(this.tableTYGH.CC_BF_BQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCC_BF_BQNull() {
                this[this.tableTYGH.CC_BF_BQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCC_BF_LJNull() {
                return this.IsNull(this.tableTYGH.CC_BF_LJColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCC_BF_LJNull() {
                this[this.tableTYGH.CC_BF_LJColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCC_JJF_BQNull() {
                return this.IsNull(this.tableTYGH.CC_JJF_BQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCC_JJF_BQNull() {
                this[this.tableTYGH.CC_JJF_BQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCC_JJF_LJNull() {
                return this.IsNull(this.tableTYGH.CC_JJF_LJColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCC_JJF_LJNull() {
                this[this.tableTYGH.CC_JJF_LJColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCC_ZXF_BQNull() {
                return this.IsNull(this.tableTYGH.CC_ZXF_BQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCC_ZXF_BQNull() {
                this[this.tableTYGH.CC_ZXF_BQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCC_ZXF_LJNull() {
                return this.IsNull(this.tableTYGH.CC_ZXF_LJColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCC_ZXF_LJNull() {
                this[this.tableTYGH.CC_ZXF_LJColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRS_BF_BQNull() {
                return this.IsNull(this.tableTYGH.RS_BF_BQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRS_BF_BQNull() {
                this[this.tableTYGH.RS_BF_BQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRS_BF_LJNull() {
                return this.IsNull(this.tableTYGH.RS_BF_LJColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRS_BF_LJNull() {
                this[this.tableTYGH.RS_BF_LJColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRS_JJF_BQNull() {
                return this.IsNull(this.tableTYGH.RS_JJF_BQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRS_JJF_BQNull() {
                this[this.tableTYGH.RS_JJF_BQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRS_JJF_LJNull() {
                return this.IsNull(this.tableTYGH.RS_JJF_LJColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRS_JJF_LJNull() {
                this[this.tableTYGH.RS_JJF_LJColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRS_ZXF_BQNull() {
                return this.IsNull(this.tableTYGH.RS_ZXF_BQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRS_ZXF_BQNull() {
                this[this.tableTYGH.RS_ZXF_BQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRS_ZXF_LJNull() {
                return this.IsNull(this.tableTYGH.RS_ZXF_LJColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRS_ZXF_LJNull() {
                this[this.tableTYGH.RS_ZXF_LJColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHJ_BF_BQNull() {
                return this.IsNull(this.tableTYGH.HJ_BF_BQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHJ_BF_BQNull() {
                this[this.tableTYGH.HJ_BF_BQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHJ_BF_LJNull() {
                return this.IsNull(this.tableTYGH.HJ_BF_LJColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHJ_BF_LJNull() {
                this[this.tableTYGH.HJ_BF_LJColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHJ_JJF_BQNull() {
                return this.IsNull(this.tableTYGH.HJ_JJF_BQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHJ_JJF_BQNull() {
                this[this.tableTYGH.HJ_JJF_BQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHJ_JJF_LJNull() {
                return this.IsNull(this.tableTYGH.HJ_JJF_LJColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHJ_JJF_LJNull() {
                this[this.tableTYGH.HJ_JJF_LJColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHJ_ZXF_BQNull() {
                return this.IsNull(this.tableTYGH.HJ_ZXF_BQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHJ_ZXF_BQNull() {
                this[this.tableTYGH.HJ_ZXF_BQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHJ_ZXF_LJNull() {
                return this.IsNull(this.tableTYGH.HJ_ZXF_LJColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHJ_ZXF_LJNull() {
                this[this.tableTYGH.HJ_ZXF_LJColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class TYGHRowChangeEvent : global::System.EventArgs {
            
            private TYGHRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TYGHRowChangeEvent(TYGHRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TYGHRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591